### .github/workflows/dependabot_pr.yml
### This workflow doesn't have access to secrets and has a read-only token
name: Dependabot PR Check
on: 
  push:
    paths:
      - poetry.lock
      - pyproject.toml
  workflow_dispatch:

jobs:
  manual-run:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/env_test.yml

  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"

  