name: Release Update

on: push

jobs:
  test-gh:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Create wheel
          run: |
            python -m pip install --upgrade pip poetry
            poetry install
            poetry build
            ls
        - name: understand env
          run: |
            ls dist
        - name: Python Semantic Release
          uses: python-semantic-release/python-semantic-release@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

        - name: Run gh CLI Command
          if: steps.release.outputs.released == 'true'
          env:
            GH_TOKEN: ${{ github.token }}
          run: |
            gh release create test-actual-files ./dist/*