name: Environment Test

on: push

jobs:
  test-gh:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Run gh CLI Command
          run: |
            gh repo list
        - name: Run gh CLI Command
          run: |
            gh issue create --body "Hello world!"